Modify `build.gradle` to add `tracing` dependency.

[source,java]
.bookcatalogue/build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/bookcatalogue/build.gradle[tag=tracing]
}
----

Also, to send tracing spans to Zipkin the minimal configuration requires you add the following dependencies to `build.gradle`:

[source,java]
.bookcatalogue/build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/bookcatalogue/build.gradle[tag=zipkin]
}
----


Append to `bookcatalogue` service `application.yml` the following snippet:

[source,yaml]
.bookcatalogue/src/main/resources/application.yml
----
include::{sourceDir}/bookcatalogue/src/main/resources/application.yml[tag=zipkin]
----

<1> Trace 100% of requests.

Previous configuration registers a Micronaut app with Consul with minimal configuration. Discover a more complete list of Configuration options at https://docs.micronaut.io/snapshot/api/io/micronaut/discovery/consul/ConsulConfiguration.html[ConsulConfiguration].

Disable consul registration in tests:

[source,yaml]
.bookcatalogue/src/main/resources/application-test.yml
----
include::{sourceDir}/bookcatalogue/src/main/resources/application-test.yml[tag=zipkin]
----

Annotate `BookController` method with `@ContinueSpan`:

[source,java]
.bookcatalogue/src/main/java/example/micronaut/bookcatalogue/BooksController.java
----
include::{sourceDir}/bookcatalogue/src/main/java/example/micronaut/bookcatalogue/BooksController.java[]
----

<1> The `@ContinueSpan` annotation will continue an existing span, wrapping the method call or reactive type.