Modify `build.gradle` to add `tracing` dependency.

[source,java]
.bookinventory/build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/bookinventory/build.gradle[tag=tracing]
}
----

Also, to send tracing spans to Zipkin the minimal configuration requires you add the following dependencies to `build.gradle`:

[source,java]
.bookinventory/build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/bookinventory/build.gradle[tag=zipkin]
}
----


Append to `bookinventory` service `application.yml` the following snippet:

[source,yaml]
.bookinventory/src/main/resources/application.yml
----
include::{sourceDir}/bookinventory/src/main/resources/application.yml[tag=zipkin]
----

<1> Trace 100% of requests.

In production, you will probably want to trace a smaller percentage of the requests. However, in order to keep this tutorial easy, we set it to trace 100%.

Disable distributed tracing in tests:

[source,yaml]
.bookinventory/src/main/resources/application-test.yml
----
include::{sourceDir}/bookinventory/src/main/resources/application-test.yml[tag=zipkin]
----

Annotate `BookController` method with `@ContinueSpan` and the method parameter with `@SpanTag`:

[source,java]
.bookinventory/src/main/java/example/micronaut/bookinventory/BooksController.java
----
include::{sourceDir}/bookinventory/src/main/java/example/micronaut/bookinventory/BooksController.java[]
----

<1> The `@ContinueSpan` annotation will continue an existing span, wrapping the method call or reactive type.
<2> The `@SpanTag` annotation can be used on method arguments to include the value of each argument within a Span's tags. When you use `@SpanTag` you need either to annotate the method with `@NewSpan` or `@ContinueSpan``

