Create the `bookrecommendation` microservice:

`mn create-app example.micronaut.bookrecommendation.bookrecommendation`

Modify `build.gradle` to add validation capabilities.

The previous command creates a folder named `bookrecommendation` and a Micronaut app inside it with
default package: `example.micronaut.bookrecommendation`.

Create an interface to map operations with `bookcatalogue` and a Micronaut Declarative HTTP Client to consume it.

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookCatalogueOperations.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookCatalogueOperations.java[]
----

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookCatalogueClient.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookCatalogueClient.java[tag=packageandimports]

include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookCatalogueClient.java[tag=harcoded]
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookCatalogueClient.java[tag=clazz]
----

The client returns a POJO. Create it in the `bookrecommendation`:
[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/Book.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/Book.java[]
----

Create an interface to map operations with `bookinventory` and a Micronaut Declarative HTTP Client to consume it.

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookInventoryOperations.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookInventoryOperations.java[]
----

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookInventoryClient.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookInventoryClient.java[tag=packageandimports]

include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookInventoryClient.java[tag=harcoded]
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookInventoryClient.java[tag=clazz]
----


Create a Controller which injects both clients.

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookController.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookController.java[]
----

`BookCatalogueClient` and `BookInventoryClient` will fail to consume the `bookcatalogue` and `bookinventory` during the tests phase.

A common pattern is to create `@Fallback` alternatives in the tests classpath.

[source,java]
.bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookInventoryClientStub.java
----
include::{sourceDir}/bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookInventoryClientStub.java[]
----

[source,java]
.bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookCatalogueClientStub.java
----
include::{sourceDir}/bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookCatalogueClientStub.java[]
----

Write a test:

[source,java]
.bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookControllerTest.java
----
include::{sourceDir}/bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookControllerTest.java[]
----

The previous controller returns a `Flowable<BookRecommendation>`. Create the `BookRecommendation` POJO:

[source,java]
.bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookRecommendation.java
----
include::{sourceDir}/bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookRecommendation.java[]
----

Edit `application.yml`

[source,yaml]
.bookrecommendation/src/main/resources/application.yml
----
include::{sourceDir}/bookrecommendation/src/main/resources/application.yml[tag=mn]
----

<1> Configure the application name. The app name will be used later in the tutorial.
<2> Configure the app to listen at port 8080

Create a file named `application-test.yml` which is used in the test environment:

[source,yaml]
.bookrecommendation/src/main/resources/application-test.yml
----
include::{sourceDir}/bookrecommendation/src/main/resources/application-test.yml[]
----

<1> Start the micronaut microservice at a random port when running the tests.

Modify `