Create the `bookcatalogue` microservice:

`mn create-app example.micronaut.bookcatalogue.bookcatalogue`

The previous command creates a folder named `bookcatalogue` and a Micronaut app inside it with
default package: `example.micronaut.bookcatalogue`.

[source,java]
.bookcatalogue/src/main/java/example/micronaut/bookcatalogue/BooksController.java
----
include::{sourceDir}/bookcatalogue/src/main/java/example/micronaut/bookcatalogue/BooksController.java[]
----

The previous controller responds a `Flowable<Book>`. Create the `Book` POJO:

[source,java]
.bookcatalogue/src/main/java/example/micronaut/bookcatalogue/Book.java
----
include::{sourceDir}/bookcatalogue/src/main/java/example/micronaut/bookcatalogue/Book.java[]
----

Write a test:

[source,java]
.bookcatalogue/src/test/java/example/micronaut/bookcatalogue/BooksControllerTest.java
----
include::{sourceDir}/bookcatalogue/src/test/java/example/micronaut/bookcatalogue/BooksControllerTest.java[]
----

Edit `application.yml`

[source,yaml]
.bookcatalogue/src/main/resources/application.yml
----
include::{sourceDir}/bookcatalogue/src/main/resources/application.yml[tag=mn]
----

<1> Configure the application name. The app name will be use by the discovery service.
<2> Configure the app to listen at port 8081

Create a file named `application-test.yml` which is used in the test environment:

[source,yaml]
.bookcatalogue/src/main/resources/application-test.yml
----
include::{sourceDir}/bookcatalogue/src/main/resources/application-test.yml[]
----

<1> Start the micronaut microservice at a random port when running the tests.